openapi: 3.0.0
info:
  title: AI Service
  version: ''
  description: The service facilitates and streamlines e-commerce processes of product marketing.
  contact:
    name: Emporix
    url: https://emporix.com
    email: documentation@emporix.com
tags:
  - name: AI Completions
    description: AI Completions
  - name: Text Generation
    description: AI Text Generation
  - name: Agent Chat
    description: Chat With Agents
  - name: Agent Template
    description: Manage Agent Templates
  - name: Agent
    description: Manage Agents
  - name: Tool
    description: Manage Tools
  - name: Token
    description: Manage Tokens
  - name: MCP Server
    description: Manage MCP Servers
  - name: Job
    description: Manage Jobs
servers:
  - url: https://api.emporix.io
paths:
  '/ai-service/{tenant}/texts':
    post:
      summary: Generating text for an object description
      operationId: POST-ai-generate-description
      description: |-
        Generates a text based on a prompt. Currently supported AI engines for text generation:
        * https://platform.openai.com/

        ***
        Prerequisite: Using the AI service requires an API token, you have to either configure your own OpenAI account, or use the Emporix one. To configure your own OpenAI token, use the configuration service by storing the token under `openAiApiToken` key.  
        
        If you don't provide your own OpenAI token, the Emporix one is used with the following limits: 3 mln input tokens and 1 mln output tokens. When you reach the limit, the next requests are rejected and you have to provide your own OpenAI token.
        Emporix uses the gpt-4o-mini model by default.
        If you want to use your own OpenAI account with a different AI model please contact our [Emporix Support Team](mailto:support@emporix.com) to negotiate the model and usage.
        ***

        ### Required scopes

        * `ai.text_manage`
      security:
        - OAuth2:
            - ai.text_manage
      tags:
        - Text Generation
  '/ai-service/{tenant}/completions':
    post:
      summary: AI Completions
      operationId: POST-ai-completions
      description: |-
        Generates a completion based on chat history. Currently supported AI engines for the completion:
        * https://platform.openai.com/


        ***
        Prerequisite: Using the AI service requires an API token, you have to either configure your own OpenAI account, or use the Emporix one. To configure your own OpenAI token, use the configuration service by storing the token under `openAiApiToken` key. 
        
        If you don't provide your own OpenAI token, the Emporix one is used with the following limits: 3 mln input tokens and 1 mln output tokens. When you reach the limit, the next requests are rejected and you have to provide your own OpenAI token. 
        Emporix uses the gpt-4o-mini model by default. If you want to use your own OpenAI account with a different AI model please contact our [Emporix Support Team](mailto:support@emporix.com) to negotiate the model and usage.
        ***

        ### Required scopes

        * `ai.completion_manage`
      security:
        - OAuth2:
            - ai.completion_manage
      tags:
        - AI Completions
  '/ai-service/{tenant}/jobs':
    get:
      summary: Get available jobs
      operationId: GET-ai-list-jobs
      description: |-
        ![Preview](https://res.cloudinary.com/saas-ag/image/upload/v1752824268/emporix/icons/preview_api1.png)
        Retrieves agent jobs.
        
        ### Required scopes

        * `ai.agent_read`
      security:
        - OAuth2:
            - ai.agent_read
      tags:
        - Job
  '/ai-service/{tenant}/jobs/{jobId}':
    get:
      summary: Get available job
      operationId: GET-ai-job
      description: |-
        ![Preview](https://res.cloudinary.com/saas-ag/image/upload/v1752824268/emporix/icons/preview_api1.png)
        Retrieves agent job.
        
        ### Required scopes

        * `ai.agent_read`
      security:
        - OAuth2:
            - ai.agent_read
      tags:
        - Job
    delete:
      summary: Delete job
      operationId: DELETE-ai-job
      description: |-
        ![Preview](https://res.cloudinary.com/saas-ag/image/upload/v1752824268/emporix/icons/preview_api1.png)
        Deletes job by given Id.
        
        ### Required scopes

        * `ai.agent_manage`
      security:
        - OAuth2:
            - ai.agent_manage
      tags:
        - Job
  '/ai-service/{tenant}/jobs/search':
    post:
      summary: Get jobs
      operationId: POST-ai-search-jobs
      description: |-
        ![Preview](https://res.cloudinary.com/saas-ag/image/upload/v1752824268/emporix/icons/preview_api1.png)
        Searches for agent templates based on the provided query.
        
        ### Required scopes

        * `ai.agent_read`
      security:
        - OAuth2:
            - ai.agent_read
      tags:
        - Job
  '/ai-service/{tenant}/agentic/chat':
    post:
      summary: Agent's Chat
      operationId: POST-ai-agents-chat
      description: |-
        ![Preview](https://res.cloudinary.com/saas-ag/image/upload/v1752824268/emporix/icons/preview_api1.png)
        Allows for communication with Emporix's agents.

        ### Required scopes

        * `ai.completion_manage`
      security:
        - OAuth2:
            - ai.completion_manage
      tags:
        - Agent Chat
  '/ai-service/{tenant}/agentic/chat-async':
    post:
      summary: Agent's Async Chat
      operationId: POST-ai-agents-chat-async
      description: |-
        ![Preview](https://res.cloudinary.com/saas-ag/image/upload/v1752824268/emporix/icons/preview_api1.png)
        Allows for communication with Emporix's agents in async way.

        ### Required scopes

        * `ai.completion_manage`
      security:
        - OAuth2:
            - ai.completion_manage
      tags:
        - Agent Chat
  '/ai-service/{tenant}/agentic/templates':
    get:
      summary: Get available agent templates
      operationId: GET-ai-list-templates
      description: |-
        ![Preview](https://res.cloudinary.com/saas-ag/image/upload/v1752824268/emporix/icons/preview_api1.png)
        Retrieves agent templates which can be later use as a base for custom agents.
        
        ### Required scopes

        * `ai.agent_read`
      security:
        - OAuth2:
            - ai.agent_read
      tags:
        - Agent Template
  '/ai-service/{tenant}/agentic/templates/search':
    post:
      summary: Search agent templates
      operationId: POST-ai-search-templates
      description: |-
        ![Preview](https://res.cloudinary.com/saas-ag/image/upload/v1752824268/emporix/icons/preview_api1.png)
        Searches for agent templates based on the provided query.
        
        ### Required scopes

        * `ai.agent_read`
      security:
        - OAuth2:
            - ai.agent_read
      tags:
        - Agent Template
  '/ai-service/{tenant}/agentic/templates/{templateId}/agent':
    post:
      summary: Create agent instance based on the template
      operationId: POST-ai-clone-template
      description: |-
        ![Preview](https://res.cloudinary.com/saas-ag/image/upload/v1752824268/emporix/icons/preview_api1.png)
        Creates an instance of the agent based of the given agent template.
        
        **Info:** Only active templates can be cloned
        
        ### Required scopes

        * `ai.agent_manage`
      security:
        - OAuth2:
            - ai.agent_manage
      tags:
        - Agent Template
  '/ai-service/{tenant}/agentic/agents':
    get:
      summary: Get agents
      operationId: GET-ai-list-agents
      description: |-
        ![Preview](https://res.cloudinary.com/saas-ag/image/upload/v1752824268/emporix/icons/preview_api1.png)
        Retrieves agent templates based on the provided query.
        
        ### Required scopes

        * `ai.agent_read`
      security:
        - OAuth2:
            - ai.agent_read
      tags:
        - Agent
  '/ai-service/{tenant}/agentic/agents/search':
    post:
      summary: Get agents
      operationId: POST-ai-search-agents
      description: |-
        ![Preview](https://res.cloudinary.com/saas-ag/image/upload/v1752824268/emporix/icons/preview_api1.png)
        Searches for agents based on the provided query.
        
        ### Required scopes

        * `ai.agent_read`
      security:
        - OAuth2:
            - ai.agent_read
      tags:
        - Agent
  '/ai-service/{tenant}/agentic/agents/{agentId}':
    get:
      summary: Get agent by Id
      operationId: GET-ai-retrieve-agent
      description: |-
        ![Preview](https://res.cloudinary.com/saas-ag/image/upload/v1752824268/emporix/icons/preview_api1.png)
        Retrieves the agent by given Id
        
        ### Required scopes

        * `ai.agent_read`
      security:
        - OAuth2:
            - ai.agent_read
      tags:
        - Agent
    put:
      summary: Upsert agent
      operationId: PUT-ai-agent
      description: |-
        ![Preview](https://res.cloudinary.com/saas-ag/image/upload/v1752824268/emporix/icons/preview_api1.png)
        Updates or creates a specified product by replacing all of its existing data with data from the request body.
        If the `metadata.version` is provided then optimistic locking is enabled and version must match the version in the database.
        
        ### Required scopes

        * `ai.agent_manage`
      security:
        - OAuth2:
            - ai.agent_manage
      tags:
        - Agent
    patch:
      summary: Partially update agent
      operationId: PATCH-ai-update-agent
      description: |-
        ![Preview](https://res.cloudinary.com/saas-ag/image/upload/v1752824268/emporix/icons/preview_api1.png)
        Partially updates a single agent document with given information.
        Single update may contain multiple partial updates in the form of an array. It contains the allowed operations list:
          - `add` (adding an item to the items list)
          - `remove` (removing an item from the items list)
          - `replace` (replacing an item with given id with new definition)
        
        ### Required scopes

        * `ai.agent_manage`
      security:
        - OAuth2:
            - ai.agent_manage
      tags:
        - Agent
    delete:
      summary: Delete agent
      operationId: DELETE-ai-delete-agent
      description: |-
        ![Preview](https://res.cloudinary.com/saas-ag/image/upload/v1752824268/emporix/icons/preview_api1.png)
        Deletes agent by given Id.
        
        ### Required scopes

        * `ai.agent_manage`
      security:
        - OAuth2:
            - ai.agent_manage
      tags:
        - Agent



  '/ai-service/{tenant}/agentic/tools':
    get:
      summary: Get tools
      operationId: GET-ai-list-tools
      description: |-
        ![Preview](https://res.cloudinary.com/saas-ag/image/upload/v1752824268/emporix/icons/preview_api1.png)
        Retrieves tools based on the provided query.
        
        ### Required scopes

        * `ai.agent_read`
      security:
        - OAuth2:
            - ai.agent_read
      tags:
        - Tool
  '/ai-service/{tenant}/agentic/tools/search':
    post:
      summary: Get tools
      operationId: POST-ai-search-tools
      description: |-
        ![Preview](https://res.cloudinary.com/saas-ag/image/upload/v1752824268/emporix/icons/preview_api1.png)
        Searches for tools based on the provided query.
        
        ### Required scopes

        * `ai.agent_read`
      security:
        - OAuth2:
            - ai.agent_read
      tags:
        - Tool
  '/ai-service/{tenant}/agentic/tools/{toolId}':
    get:
      summary: Get tool by Id
      operationId: GET-ai-retrieve-tool
      description: |-
        ![Preview](https://res.cloudinary.com/saas-ag/image/upload/v1752824268/emporix/icons/preview_api1.png)
        Retrieves the tool by given Id
        
        ### Required scopes

        * `ai.agent_read`
      security:
        - OAuth2:
            - ai.agent_read
      tags:
        - Tool
    put:
      summary: Upsert tool
      operationId: PUT-ai-upsert-tool
      description: |-
        ![Preview](https://res.cloudinary.com/saas-ag/image/upload/v1752824268/emporix/icons/preview_api1.png)
        Updates or creates a specified tool by replacing all of its existing data with data from the request body.
        If the `metadata.version` is provided then optimistic locking is enabled and version must match the version in the database.
        
        ### Required scopes

        * `ai.agent_manage`
      security:
        - OAuth2:
            - ai.agent_manage
      tags:
        - Tool
    patch:
      summary: Partially update tool
      operationId: PATCH-ai-update-tool
      description: |-
        ![Preview](https://res.cloudinary.com/saas-ag/image/upload/v1752824268/emporix/icons/preview_api1.png)
        Partially updates a single tool document with given information.
        Single update may contain multiple partial updates in the form of an array. It contains the allowed operations list:
          - `add` (adding an item to the items list)
          - `remove` (removing an item from the items list)
          - `replace` (replacing an item with given id with new definition)
        
        ### Required scopes

        * `ai.agent_manage`
      security:
        - OAuth2:
            - ai.agent_manage
      tags:
        - Tool
    delete:
      summary: Delete tool
      operationId: DELETE-ai-delete-tool
      description: |-
        ![Preview](https://res.cloudinary.com/saas-ag/image/upload/v1752824268/emporix/icons/preview_api1.png)
        Deletes tool by given Id.
        
        ***Important***: If tool is being used by an agent then delete operation is not possible without `force` flag set to `true`.
        
        ### Required scopes

        * `ai.agent_manage`
      security:
        - OAuth2:
            - ai.agent_manage
      tags:
        - Tool


  '/ai-service/{tenant}/agentic/tokens':
    get:
      summary: Get tokens
      operationId: GET-ai-list-tokens
      description: |-
        ![Preview](https://res.cloudinary.com/saas-ag/image/upload/v1752824268/emporix/icons/preview_api1.png)
        Retrieves tokens based on the provided query.
        
        ### Required scopes

        * `ai.agent_read`
      security:
        - OAuth2:
            - ai.agent_read
      tags:
        - Token
  '/ai-service/{tenant}/agentic/tokens/search':
    post:
      summary: Get tokens
      operationId: POST-ai-search-tokens
      description: |-
        ![Preview](https://res.cloudinary.com/saas-ag/image/upload/v1752824268/emporix/icons/preview_api1.png)
        Searches for tokens based on the provided query.
        
        ### Required scopes

        * `ai.agent_read`
      security:
        - OAuth2:
            - ai.agent_read
      tags:
        - Token
  '/ai-service/{tenant}/agentic/tokens/{tokenId}':
    get:
      summary: Get token by Id
      operationId: GET-ai-retrieve-token
      description: |-
        ![Preview](https://res.cloudinary.com/saas-ag/image/upload/v1752824268/emporix/icons/preview_api1.png)
        Retrieves the token by given Id
        
        ### Required scopes

        * `ai.agent_read`
      security:
        - OAuth2:
            - ai.agent_read
      tags:
        - Token
    put:
      summary: Upsert token
      operationId: PUT-ai-upsert-token
      description: |-
        ![Preview](https://res.cloudinary.com/saas-ag/image/upload/v1752824268/emporix/icons/preview_api1.png)
        Updates or creates a specified token by replacing all of its existing data with data from the request body.
        If the `metadata.version` is provided then optimistic locking is enabled and version must match the version in the database.
        
        **Important**: The `value` field cannot be updated, once created token cannot change `value` field.
        
        ### Required scopes

        * `ai.agent_manage`
      security:
        - OAuth2:
            - ai.agent_manage
      tags:
        - Token
    patch:
      summary: Partially update token
      operationId: PATCH-ai-update-token
      description: |-
        ![Preview](https://res.cloudinary.com/saas-ag/image/upload/v1752824268/emporix/icons/preview_api1.png)
        Partially updates a single token document with given information.
        Single update may contain multiple partial updates in the form of an array. It contains the allowed operations list:
          - `add` (adding an item to the items list)
          - `remove` (removing an item from the items list)
          - `replace` (replacing an item with given id with new definition)
        
        **Important**: The `value` field cannot be updated, once created token cannot change `value` field.
        
        ### Required scopes

        * `ai.agent_manage`
      security:
        - OAuth2:
            - ai.agent_manage
      tags:
        - Token
    delete:
      summary: Delete token
      operationId: DELETE-ai-delete-token
      description: |-
        ![Preview](https://res.cloudinary.com/saas-ag/image/upload/v1752824268/emporix/icons/preview_api1.png)
        Deletes tokens by given Id.
        
        
        ***Important***: If token is being used by an agent or by an mcp server then delete operation is not possible without `force` flag set to `true`.
        
        ### Required scopes

        * `ai.agent_manage`
      security:
        - OAuth2:
            - ai.agent_manage
      tags:
        - Token


  '/ai-service/{tenant}/agentic/mcp-servers':
    get:
      summary: Get mcp servers
      operationId: GET-ai-list-mcp-servers
      description: |-
        ![Preview](https://res.cloudinary.com/saas-ag/image/upload/v1752824268/emporix/icons/preview_api1.png)
        Retrieves mcp servers based on the provided query.
        
        ### Required scopes

        * `ai.agent_read`
      security:
        - OAuth2:
            - ai.agent_read
      tags:
        - MCP Server
  '/ai-service/{tenant}/agentic/mcp-servers/search':
    post:
      summary: Get mcp servers
      operationId: POST-ai-search-mcp-servers
      description: |-
        ![Preview](https://res.cloudinary.com/saas-ag/image/upload/v1752824268/emporix/icons/preview_api1.png)
        Searches for mcp servers based on the provided query.
        
        ### Required scopes

        * `ai.agent_read`
      security:
        - OAuth2:
            - ai.agent_read
      tags:
        - MCP Server
  '/ai-service/{tenant}/agentic/mcp-servers/{mcpServerId}':
    get:
      summary: Get mcp server by Id
      operationId: GET-ai-retrieve-mcp-server
      description: |-
        ![Preview](https://res.cloudinary.com/saas-ag/image/upload/v1752824268/emporix/icons/preview_api1.png)
        Retrieves the mcp server by given Id
        
        ### Required scopes

        * `ai.agent_read`
      security:
        - OAuth2:
            - ai.agent_read
      tags:
        - MCP Server
    put:
      summary: Upsert mcp server
      operationId: PUT-ai-upsert-mcp-server
      description: |-
        ![Preview](https://res.cloudinary.com/saas-ag/image/upload/v1752824268/emporix/icons/preview_api1.png)
        Updates or creates a specified mcp server by replacing all of its existing data with data from the request body.
        If the `metadata.version` is provided then optimistic locking is enabled and version must match the version in the database.

        ### Required scopes

        * `ai.agent_manage`
      security:
        - OAuth2:
            - ai.agent_manage
      tags:
        - MCP Server
    patch:
      summary: Partially update mcp server
      operationId: PATCH-ai-update-mcp-server
      description: |-
        ![Preview](https://res.cloudinary.com/saas-ag/image/upload/v1752824268/emporix/icons/preview_api1.png)
        Partially updates a single mcp server document with given information.
        Single update may contain multiple partial updates in the form of an array. It contains the allowed operations list:
          - `add` (adding an item to the items list)
          - `remove` (removing an item from the items list)
          - `replace` (replacing an item with given id with new definition)

        ### Required scopes

        * `ai.agent_manage`
      security:
        - OAuth2:
            - ai.agent_manage
      tags:
        - MCP Server
    delete:
      summary: Delete mcp server
      operationId: DELETE-ai-delete-mcp-server
      description: |-
        ![Preview](https://res.cloudinary.com/saas-ag/image/upload/v1752824268/emporix/icons/preview_api1.png)
        Deletes mcp server by given Id. 
        
        ***Important***: If mcp server is being used by an agent then delete operation is not possible without `force` flag set to `true`.
        
        ### Required scopes

        * `ai.agent_manage`
      security:
        - OAuth2:
            - ai.agent_manage
      tags:
        - MCP Server


components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          scopes:
            ai.text_manage: Needed to execute actions related to the text generation.
            ai.completion_manage: Needed to execute actions related to the AI completions.
            ai.agent_read: Needed to read AI agents
            ai.agent_manage: Needed to manage AI agents
          tokenUrl: 'https://api.emporix.io/oauth/token'