export enum RoleCode {
  VIEWER = 'viewer',
  EDITOR = 'editor',
  MANAGER = 'manager',
  ADMINISTRATOR = 'administrator',
  LEGAL_ENTITY_VIEWER = 'legalEntityViewer',
}

export enum ResourcesDCP {
  COMPANIES = 'companies',
  CUSTOMERS = 'customers',
  COUPONS = 'coupons',
  QUOTES = 'quotes',
  STATUS_CODES = 'statusCodes',
  ORDERS = 'orders',
  SEPA = 'sepa',
  RETURNS = 'returns',
  CATALOGS = 'catalogs',
  CATEGORIES = 'categories',
  PRODUCTS = 'products',
  PRODUCT_TEMPLATES = 'productTemplates',
  LABELS = 'labels',
  SUPPLIERS = 'suppliers',
  BRANDS = 'brands',
  PRICE_MODELS = 'priceModels',
  PRICE_LISTS = 'priceLists',
  SITES = 'sites',
  DELIVERY_METHODS = 'deliveryMethods',
  DELIVERY_TIMES = 'deliveryTimes',
  UNITS = 'units',
  TAXES = 'taxes',
  COUNTRIES = 'countries',
  CURRENCIES = 'currencies',
  LANGUAGES = 'languages',
  SYSTEM_PREFERENCES = 'systemPreferences',
  MIXIN_SCHEMAS = 'mixinSchemas',
  USERS_AND_GROUPS = 'usersAndGroups',
  WEBHOOKS = 'webhooks',
  EXTENSIONS = 'extensions',
  FEATURE_TOGGLES = 'featureToggles',
  STATISTICS = 'statistics',
  SEGMENTS = 'segments',
  CUSTOM_INSTANCES = 'customInstances',
  LEGAL_ENTITIY_ORDERS = 'legalEntityOrders',
}

export enum ResourcesOE {
  DIGITAL_PROCESSES = 'digitalProcesses',
  FORMS = 'forms',
  SCHEDULERS = 'schedulers',
  BUSINESS_RULES = 'businessRules',
}
