name: (algolia-synonyms) Build and deploy (dev, stage) to Firebase
on:
  push:
    branches:
      - master
    paths:
      - 'algolia-synonyms/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./algolia-synonyms

    strategy:
      matrix:
        node: [20.x]

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
          cache-dependency-path: ./algolia-synonyms/yarn.lock

      - run: yarn install

      - run: yarn build:dev
      - uses: FirebaseExtended/action-hosting-deploy@v0
        id: firebase-hosting-deploy-dev
        with:
          firebaseToolsVersion: "12.9.1"
          firebaseServiceAccount: "${{ secrets.MD_EXTS_FIREBASE_SA_DEV }}"
          projectId: frontend-extensions-develop
          channelId: live
          target: emporix-algolia-synonyms-develop

      - run: yarn build:stage
      - uses: FirebaseExtended/action-hosting-deploy@v0
        id: firebase-hosting-deploy-stage
        with:
          firebaseToolsVersion: "12.9.1"
          firebaseServiceAccount: "${{ secrets.MD_EXTS_FIREBASE_SA_STAGE }}"
          projectId: frontend-extensions-stage
          channelId: live
          target: emporix-algolia-synonyms-stage
