name: (site-settings) Build and deploy (prod) to Firebase

on:
  push:
    tags:
      - site-settings-*
    paths:
      - 'site-settings/**'
  workflow_dispatch:
    inputs:
      tag:
        description: "Deploy the tag."
        required: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./site-settings

    strategy:
      matrix:
        node: [20.x]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
          cache-dependency-path: ./site-settings/yarn.lock

      - run: yarn install

      - run: yarn build:prod
      - uses: FirebaseExtended/action-hosting-deploy@v0
        id: firebase-hosting-deploy
        with:
          firebaseToolsVersion: "12.9.1"
          firebaseServiceAccount: "${{ secrets.MD_EXTS_FIREBASE_SA }}"
          projectId: frontend-extensions
          channelId: live
          target: emporix-site-settings
